// Preload: minimal, explicit IPC surface. No Node access from the renderer.
'use strict';

const { contextBridge, ipcRenderer, webUtils } = require('electron');

function listen(channel, fn) {
  const handler = (_event, payload) => fn(payload);
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

contextBridge.exposeInMainWorld('mudex', {
  showNotification: (sessionTitle, sessionId, status) => ipcRenderer.invoke('mudex:show-notification', { sessionTitle, sessionId, status }),
  onNotificationClick: (fn) => listen('mudex:notification-click', fn),
  pickFolder: () => ipcRenderer.invoke('mudex:pick-folder'),
  listDir: (dirPath) => ipcRenderer.invoke('mudex:list-dir', { path: dirPath }),
  watchDirectory: (root, directory) => ipcRenderer.invoke('mudex:watch-directory', { root, directory }),
  unwatchDirectory: (root, directory) => ipcRenderer.invoke('mudex:unwatch-directory', { root, directory }),
  createEntry: (dirPath, name, kind) => ipcRenderer.invoke('mudex:create-entry', { dir: dirPath, name, kind }),
  renameEntry: (rootPath, entryPath, name) => ipcRenderer.invoke('mudex:rename-entry', { root: rootPath, path: entryPath, name }),
  deleteEntry: (rootPath, entryPath) => ipcRenderer.invoke('mudex:delete-entry', { root: rootPath, path: entryPath }),
  revealEntry: (rootPath, entryPath) => ipcRenderer.invoke('mudex:reveal-entry', { root: rootPath, path: entryPath }),
  searchFiles: (cwd, query, options) => ipcRenderer.invoke('mudex:search-files', { cwd, query, options }),
  searchInFiles: (cwd, query, options) => ipcRenderer.invoke('mudex:search-in-files', { cwd, query, options }),
  readFile: (filePath) => ipcRenderer.invoke('mudex:read-file', { path: filePath }),
  pickFiles: () => ipcRenderer.invoke('mudex:pick-files'),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  savePastedImage: (name, base64, mime) => ipcRenderer.invoke('mudex:save-pasted-image', { name, base64, mime }),
  exportMarkdown: (title, markdown) => ipcRenderer.invoke('mudex:export-markdown', { title, markdown }),
  commitMessage: (cwd, files) => ipcRenderer.invoke('mudex:commit-message', { cwd, files }),
  exportBackup: (title, json) => ipcRenderer.invoke('mudex:export-backup', { title, json }),
  pickBackup: () => ipcRenderer.invoke('mudex:pick-backup'),
  readFileBytes: (filePath) => ipcRenderer.invoke('mudex:read-file-bytes', { path: filePath }),
  openFileDefault: (filePath) => ipcRenderer.invoke('mudex:open-file-default', { path: filePath }),
  openExternalLink: (url) => ipcRenderer.invoke('mudex:open-external-link', { url }),
  gitNumstat: (cwd) => ipcRenderer.invoke('mudex:git-numstat', { cwd }),
  verifyScripts: (cwd) => ipcRenderer.invoke('mudex:verify-scripts', { cwd }),
  verifyRun: (cwd, script) => ipcRenderer.invoke('mudex:verify-run', { cwd, script }),
  revertFiles: (cwd, files) => ipcRenderer.invoke('mudex:revert-files', { cwd, files }),
  checkpointCreate: (cwd, sessionId) => ipcRenderer.invoke('mudex:checkpoint-create', { cwd, sessionId }),
  checkpointRestore: (cwd, sessionId, id) => ipcRenderer.invoke('mudex:checkpoint-restore', { cwd, sessionId, id }),
  writeFile: (filePath, content, expectedOriginal) => ipcRenderer.invoke('mudex:write-file', { path: filePath, content, expectedOriginal }),
  getSettings: () => ipcRenderer.invoke('mudex:get-settings'),
  saveSettings: (patch) => ipcRenderer.invoke('mudex:save-settings', patch),
  cliTest: () => ipcRenderer.invoke('mudex:cli-test'),
  chatStart: (prompt, cwd, threadKey, mspSessionId, plan, overrides) =>
    ipcRenderer.invoke('mudex:chat-start', { prompt, cwd, threadKey, mspSessionId, plan, overrides }),
  chatCancel: (reqId) => ipcRenderer.invoke('mudex:chat-cancel', { reqId }),
  mspPrewarm: (cwd) => ipcRenderer.invoke('msp:prewarm', { cwd }),
  mspDecide: (key, choiceId, feedback) => ipcRenderer.invoke('msp:decide', { key, choiceId, feedback }),
  mspUserInputAnswer: (key, answers) => ipcRenderer.invoke('msp:user-input-answer', { key, answers }),
  mspUserInputCancel: (key) => ipcRenderer.invoke('msp:user-input-cancel', { key }),
  mspSessions: (cwd) => ipcRenderer.invoke('msp:sessions', { cwd }),
  mspResume: (threadKey, mspSessionId, cwd) => ipcRenderer.invoke('msp:resume', { threadKey, mspSessionId, cwd }),
  mspUsage: (cwd) => ipcRenderer.invoke('msp:usage', { cwd }),
  mspModels: (cwd) => ipcRenderer.invoke('msp:models', { cwd }),
  mspSetModel: (threadKey, modelId) => ipcRenderer.invoke('msp:set-model', { threadKey, modelId }),
  mspSetApprovalMode: (threadKey, mode) => ipcRenderer.invoke('msp:set-approval-mode', { threadKey, mode }),
  mspSetReasoning: (threadKey, effort) => ipcRenderer.invoke('msp:set-reasoning', { threadKey, effort }),
  mspWarmup: (cwd) => ipcRenderer.invoke('msp:warmup', { cwd }),
  codexSessions: (cwd) => ipcRenderer.invoke('codex:sessions', { cwd }),
  codexRead: (sessionId, cwd) => ipcRenderer.invoke('codex:read', { sessionId, cwd }),
  codexQueue: (sessionId, cwd, context) => ipcRenderer.invoke('codex:queue', { sessionId, cwd, context }),
  claudeSessions: (cwd) => ipcRenderer.invoke('claude:sessions', { cwd }),
  claudeRead: (sessionId, cwd) => ipcRenderer.invoke('claude:read', { sessionId, cwd }),
  claudeQueue: (sessionId, cwd, context) => ipcRenderer.invoke('claude:queue', { sessionId, cwd, context }),
  onMspItem: (fn) => listen('msp:item', fn),
  onMspReady: (fn) => listen('msp:ready', fn),
  onMspPrewarmError: (fn) => listen('msp:prewarm-error', fn),
  onMspApproval: (fn) => listen('msp:approval', fn),
  onMspApprovalResolved: (fn) => listen('msp:approval-resolved', fn),
  onMspUserInput: (fn) => listen('msp:user-input', fn),
  onMspUserInputSettled: (fn) => listen('msp:user-input-settled', fn),
  onMspUsage: (fn) => listen('msp:usage', fn),
  onMspTokens: (fn) => listen('msp:tokens', fn),
  onMspSessionsChanged: (fn) => listen('msp:sessions-changed', fn),
  onMspHostDead: (fn) => listen('msp:host-dead', fn),
  onMspGateFallback: (fn) => listen('msp:gate-fallback', fn),
  onMspTodos: (fn) => listen('msp:todos', fn),
  onHookResult: (fn) => listen('mudex:hook-result', fn),
  hookTest: (command, cwd) => ipcRenderer.invoke('mudex:hook-test', { command, cwd }),
  onMspMcpHealth: (fn) => listen('msp:mcp-health', fn),
  onMspMcpUnavailable: (fn) => listen('msp:mcp-unavailable', fn),
  gitStatus: (cwd) => ipcRenderer.invoke('mudex:git-status', { cwd }),
  gitShow: (cwd, file) => ipcRenderer.invoke('mudex:git-show', { cwd, file }),
  gitStage: (cwd, files, staged) => ipcRenderer.invoke('mudex:git-stage', { cwd, files, staged }),
  gitCommit: (cwd, message) => ipcRenderer.invoke('mudex:git-commit', { cwd, message }),
  gitBranch: (cwd) => ipcRenderer.invoke('mudex:git-branch', { cwd }),
  gitBranches: (cwd) => ipcRenderer.invoke('mudex:git-branches', { cwd }),
  gitCheckout: (cwd, branch) => ipcRenderer.invoke('mudex:git-checkout', { cwd, branch }),
  gitCreateBranch: (cwd, branch) => ipcRenderer.invoke('mudex:git-create-branch', { cwd, branch }),
  gitPull: (cwd) => ipcRenderer.invoke('mudex:git-pull', { cwd }),
  gitPush: (cwd) => ipcRenderer.invoke('mudex:git-push', { cwd }),
  gitClone: (url, target) => ipcRenderer.invoke('mudex:git-clone', { url, target }),
  sessionsSave: (sessions) => ipcRenderer.invoke('mudex:sessions-save', { sessions }),
  sessionsLoad: () => ipcRenderer.invoke('mudex:sessions-load'),
  rendererStateGet: (key) => ipcRenderer.invoke('mudex:state-get', { key }),
  rendererStateSet: (key, value) => ipcRenderer.invoke('mudex:state-set', { key, value }),
  browserShow: (tabId, home, initialUrl) => ipcRenderer.invoke('browser:show', { tabId, home, initialUrl }),
  browserHide: (tabId) => ipcRenderer.invoke('browser:hide', { tabId }),
  browserClose: (tabId) => ipcRenderer.invoke('browser:close', { tabId }),
  browserBounds: (bounds) => ipcRenderer.invoke('browser:bounds', bounds),
  browserNavigate: (tabId, url) => ipcRenderer.invoke('browser:navigate', { tabId, url }),
  browserBack: (tabId) => ipcRenderer.invoke('browser:back', { tabId }),
  browserForward: (tabId) => ipcRenderer.invoke('browser:forward', { tabId }),
  browserReload: (tabId) => ipcRenderer.invoke('browser:reload', { tabId }),
  browserStop: (tabId) => ipcRenderer.invoke('browser:stop', { tabId }),
  browserFind: (tabId, text, forward, findNext) => ipcRenderer.invoke('browser:find', { tabId, text, forward, findNext }),
  browserState: (tabId) => ipcRenderer.invoke('browser:state', { tabId }),
  browserSource: (tabId, max) => ipcRenderer.invoke('browser:source', { tabId, max }),
  browserTabs: () => ipcRenderer.invoke('browser:tabs'),
  browserMcpCmd: () => ipcRenderer.invoke('browser:mcp-cmd'),
  browserMcpRegister: () => ipcRenderer.invoke('browser:mcp-register'),
  skills: (action, payload) => ipcRenderer.invoke('mudex:skills', { ...(payload || {}), action }),
  browserHealth: () => ipcRenderer.invoke('browser:health'),
  onBrowserEvent: (fn) => listen('browser:event', fn),
  termStart: (tabId, shell, cwd, seq) => ipcRenderer.invoke('term:start', { tabId, shell, cwd, seq }),
  termInput: (tabId, text) => ipcRenderer.invoke('term:input', { tabId, text }),
  termKill: (tabId) => ipcRenderer.invoke('term:kill', { tabId }),
  onTermEvent: (fn) => listen('term:event', fn),
  onChatChunk: (fn) => listen('mudex:chat-chunk', fn),
  onChatStderr: (fn) => listen('mudex:chat-stderr', fn),
  onChatDone: (fn) => listen('mudex:chat-done', fn),
  onWorkspaceChanged: (fn) => listen('mudex:workspace-changed', fn),
  onWorkspaceWatchError: (fn) => listen('mudex:workspace-watch-error', fn),
});
